### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by beettlefor** [claudioviviani/wordbrutepress#2]
File "wordbrutepress.py", line 376, in <module>
    if connection(url,user,UA,UA,timeout,brtmd) == "OK":
  File "wordbrutepress.py", line 228, in connection
    if responseCMS(response) == "1":
  File "wordbrutepress.py", line 203, in responseCMS
    if response['set-cookie'].split(" ")[-1] == "httponly":
KeyError: 'set-cookie'

**Comment by claudioviviani** [comment]
Hi, i can't replace the issue.
Can you write me other specifications? Python version? Wordpress version?

Thanks

**Comment by claudioviviani** [comment]
no response, can't replace the issue.

**Comment by tyliec** [comment]
I'm having the same issue
